import java.sql.*;

class InsertEmp2_autoGeneratedKeys_Statement {

	public static void main(String argv[]) throws ClassNotFoundException,SQLException {

		Class.forName("oracle.jdbc.driver.OracleDriver");
		Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl2", "scott", "tiger");
	    
	  //新增員工
    String insert_stmt = 
        	"INSERT INTO emp2 (empno,ename,job,hiredate,sal,comm,deptno) VALUES (emp2_seq.NEXTVAL, '吳永志1', 'MANAGER', to_date('2005-01-01','yyyy-mm-dd'), 5000, 500, 10)";
		String cols[] = { "EMPNO" }; //或 int cols[] = {1};
		Statement stmt = con.createStatement();
		stmt.executeUpdate(insert_stmt, cols);
		
		//掘取對應的自增主鍵值
		ResultSet rsKeys = stmt.getGeneratedKeys();
		ResultSetMetaData rsmd = rsKeys.getMetaData();
		int columnCount = rsmd.getColumnCount();
		if (rsKeys.next()) {
			do {
				for (int i = 1; i <= columnCount; i++) {
					String key = rsKeys.getString(i);
					System.out.println("自增主鍵值(i=" + i + ") = " + key +"(剛新增成功的員工編號)");
				}
			} while (rsKeys.next());
		} else {
			System.out.println("NO KEYS WERE GENERATED.");
		}
		
		//查詢員工
		Statement stmt2 = con.createStatement();
		ResultSet rs = stmt2.executeQuery("SELECT * from EMP2 order by empno");		
		while (rs.next()) {
			String str1 = rs.getString(1);
			String str2 = rs.getString(2);

			System.out.print(" EMPNO= " + str1);
			System.out.print(" ENAME= " + str2);
			System.out.print("\n");
		}

		con.close();

	}
}